-- Insert Places for Melbourne (Restaurants & Cafes)
-- Category mapped to 'food' for all items.
-- Address is appended to the 'notes' field.

INSERT INTO places (name, city, category, rating, is_kid_friendly, notes, google_map_url) VALUES
-- 🍜 Asian Road
('친 친 (Chin Chin)', '멜버른', 'food', 4.5, false, '멜버른에서 가장 유명한 퓨전 태국 레스토랑입니다. 항상 대기 줄이 길지만, 힙한 분위기와 "킹피쉬 사시미", "마사만 커리" 맛은 기다릴 가치가 있습니다. [주소] 125 Flinders Ln, Melbourne VIC 3000', 'https://maps.google.com/?q=Chin+Chin+Melbourne'),
('하카타 겐스케 (Hakata Gensuke Ramen)', '멜버른', 'food', 4.6, true, '일본 본토 맛을 그대로 재현한 진한 돈코츠 라멘 전문점입니다. 면 굵기와 익힘 정도를 선택할 수 있습니다. [주소] 168 Russell St, Melbourne VIC 3000', 'https://maps.google.com/?q=Hakata+Gensuke+Melbourne'),
('상하이 스트리트 (Shanghai Street Dumpling)', '멜버른', 'food', 4.4, true, '육즙이 터지는 "샤오롱바오(소룡포)"와 바삭한 "군만두" 맛집입니다. 가성비가 훌륭해 언제나 붐빕니다. [주소] 342 Little Bourke St, Melbourne VIC 3000', 'https://maps.google.com/?q=Shanghai+Street+Dumpling+Melbourne'),
('메콩 베트남 (Mekong Vietnam)', '멜버른', 'food', 4.3, true, '빌 클린턴 전 미국 대통령이 두 그릇이나 먹고 갔다는 전설의 쌀국수 집입니다. 진하고 깊은 국물 맛이 일품입니다. [주소] 241 Swanston St, Melbourne VIC 3000', 'https://maps.google.com/?q=Mekong+Vietnam+Melbourne'),
('락사 킹 (Laksa King)', '멜버른', 'food', 4.7, true, '멜버른 최고의 락사(Laksa) 맛집으로 꼽히는 곳입니다. 얼큰하고 코코넛 향 가득한 국물이 해장에 최고입니다. [주소] 6-12 Pin Oak Cres, Flemington VIC 3031', 'https://maps.google.com/?q=Laksa+King+Flemington'),
('로즈 가든 BBQ (Rose Garden BBQ)', '멜버른', 'food', 4.5, true, '저렴한 가격에 푸짐한 중국식 덮밥을 먹을 수 있는 가성비 끝판왕입니다. 오리구이와 닭고기 덮밥이 유명합니다. [주소] 435 Elizabeth St, Melbourne VIC 3000', 'https://maps.google.com/?q=Rose+Garden+BBQ+Melbourne'),
('소이 38 (Soi 38)', '멜버른', 'food', 4.6, false, '주차장 구석에 숨겨진 보석 같은 태국 식당입니다. 방콕 현지 느낌 물씬 나는 "보트 누들"을 저렴하게 팝니다. [주소] 38 Royal Ln, Melbourne VIC 3000', 'https://maps.google.com/?q=Soi+38+Melbourne'),
('두디 파이당 (Dodee Paidang)', '멜버른', 'food', 4.3, false, '매운맛 조절이 가능한 태국 똠얌 국수 맛집입니다. 지하에 있어 아지트 같은 느낌을 줍니다. [주소] Basement/353 Little Collins St, Melbourne VIC 3000', 'https://maps.google.com/?q=Dodee+Paidang+Melbourne'),
('드래곤 핫팟 (Dragon Hot Pot)', '멜버른', 'food', 4.4, true, '내가 원하는 재료를 담아 무게를 달아 계산하는 마라탕 전문점입니다. 국물 맛이 아주 진하고 중독적입니다. [주소] 213 Russell St, Melbourne VIC 3000', 'https://maps.google.com/?q=Dragon+Hot+Pot+Melbourne'),
('스탈락티테스 (Stalactites)', '멜버른', 'food', 4.2, true, '24시간 영업하는 그리스 식당으로, 천장의 종유석 장식이 독특합니다. 양고기 수블라키(Souvlaki)가 대표 메뉴입니다. [주소] 177/183 Lonsdale St, Melbourne VIC 3000', 'https://maps.google.com/?q=Stalactites+Melbourne'),

-- 🍔 Burger & Western
('로얄 스택스 (Royal Stacks)', '멜버른', 'food', 4.5, true, '쉑쉑버거의 대항마로 불리는 멜버른 로컬 버거 브랜드입니다. 패티 육즙과 치즈 소스의 조화가 완벽합니다. [주소] 470 Collins St, Melbourne VIC 3000', 'https://maps.google.com/?q=Royal+Stacks+Melbourne'),
('부처스 다이너 (Butcher''s Diner)', '멜버른', 'food', 4.4, false, '정육점에서 운영하는 24시간 다이너입니다. 늦은 밤에 먹는 스테이크 샌드위치와 버거가 환상적입니다. [주소] 10 Bourke St, Melbourne VIC 3000', 'https://maps.google.com/?q=Butchers+Diner+Melbourne'),
('유니버셜 레스토랑 (Universal Restaurant)', '멜버른', 'food', 4.3, true, ' "얼굴보다 큰 치킨 파마(Chicken Parma)"로 유명한 이탈리안 식당입니다. 엄청난 양과 저렴한 가격으로 학생들에게 인기입니다. [주소] 141 Lygon St, Carlton VIC 3053', 'https://maps.google.com/?q=Universal+Restaurant+Carlton'),
('이지스 (Easey''s)', '멜버른', 'food', 4.6, false, '건물 옥상에 있는 기차(Train) 안에서 햄버거를 먹는 독특한 경험을 할 수 있습니다. 뷰도 좋고 버거 맛도 훌륭합니다. [주소] 3/48 Easey St, Collingwood VIC 3066', 'https://maps.google.com/?q=Easeys+Collingwood'),

-- ☕ Cafe & Bakery
('룬 크로아상 (Lune Croissanterie)', '멜버른', 'food', 4.8, true, '뉴욕타임스가 "세계 최고의 크로아상"이라고 극찬한 곳입니다. 겉바속촉의 정석을 맛볼 수 있습니다. [주소] 119 Rose St, Fitzroy VIC 3065', 'https://maps.google.com/?q=Lune+Croissanterie+Fitzroy'),
('하이어 그라운드 (Higher Ground)', '멜버른', 'food', 4.7, false, '옛 발전소를 개조해 층고가 높고 웅장한 인테리어를 자랑합니다. 리코타 핫케이크 비주얼이 예술입니다. [주소] 650 Little Bourke St, Melbourne VIC 3000', 'https://maps.google.com/?q=Higher+Ground+Melbourne'),
('더 하드웨어 소사이어티 (The Hardware Société)', '멜버른', 'food', 4.6, true, '멜버른 브런치 문화를 이끄는 곳 중 하나입니다. 프랑스 스타일의 섬세하고 예쁜 브런치 메뉴가 많습니다. [주소] 10 Katherine Pl, Melbourne VIC 3000', 'https://maps.google.com/?q=The+Hardware+Societe+Melbourne'),
('브라더 바바 부단 (Brother Baba Budan)', '멜버른', 'food', 4.5, false, '천장에 의자가 매달려 있는 인테리어로 유명합니다. 커피 맛에 집중하는 진지한 카페로, 플랫 화이트가 맛있습니다. [주소] 359 Little Bourke St, Melbourne VIC 3000', 'https://maps.google.com/?q=Brother+Baba+Budan'),
('패트리샤 커피 브루어스 (Patricia Coffee Brewers)', '멜버른', 'food', 4.6, false, '간판도 없고 의자도 거의 없는 "서서 마시는" 커피 바입니다. 오직 커피 맛 하나로 승부하는 곳입니다. [주소] Rear of 493-495 Little Bourke St, Melbourne VIC 3000', 'https://maps.google.com/?q=Patricia+Coffee+Brewers'),
('브루네티 클래시코 (Brunetti Classico)', '멜버른', 'food', 4.5, true, '"리틀 이탈리아"라 불리는 라이곤 스트리트(Lygon St)의 랜드마크입니다. 수십 종류의 케이크와 젤라또, 커피를 즐길 수 있는 대형 카페입니다. [주소] 380 Lygon St, Carlton VIC 3053', 'https://maps.google.com/?q=Brunetti+Classico+Carlton');
